spring:
  datasource:
    url: jdbc:mysql://ddareunging-dev.cnqwttc2liwc.ap-northeast-2.rds.amazonaws.com:3306/ddareunging
    username: root
    password: cotato9thddareunging11!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode:never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

weatherApi:
  serviceKey: 2eq29jtw%2FkcXgG36iZ8lq6RpzyH8q73fJvW9DwSxRduZG%2FApq0y0EXCzW1aNLj%2BzE1nQvOJDzh7wff2gr2YJsQ%3D%3D

resources:
  location: C:/Users/jooye/Ddareunging_Server/src/main/resources # 개발 환경
  real.properties: # 운영 환경 추가해야 함